### ISSUE TITLE
Does bitproto support `union`?

### ISSUE THREAD

**Issue by chenlijun99** [hit9/bitproto#43]
Hi. First, thanks for this very cool project!
I have one question: does bitproto support `union` (or something like protobuf's [`oneof`](https://developers.google.com/protocol-buffers/docs/proto3#using_oneof))? It would be useful for protocol frames where the deserialization of the remaining bytes depends on some kind of frame id in the header.

I tried to look into https://bitproto.readthedocs.io/en/latest/language.html, but unfortunately didn't find anything.

**Comment by hit9** [comment]
Hello, the `union` or `oneof` feature is not supported.

**Comment by chenlijun99** [comment]
Hi. Thanks for the confirmation!
If there is no plan no support this feature, then I guess this issue can be closed.

**Comment by hit9** [comment]
Hmm, No such plan so far.
