### ISSUE TITLE
Ambiguity about the functionality of Encode/Decode

### ISSUE THREAD

**Issue by zzz00yx** [hit9/bitproto#50]
For byte-aligned field, Encode/Decode overwrite the dest. For non-byte-aligned field, Encode/Decode is just a BitOR

Message definition:
```
message Fipr {
    uint1 api_type = 1
    uint5 engine_id = 2
    uint13 pre_install_data = 3
}
message Flit {
    uint32 dw0 = 1
    uint32 dw1 = 2
    uint32 dw2 = 3
    uint32 dw3 = 4
}
```

Test code:
```cpp
TEST(BitProto, 0) {
    Fipr fipr{};
    uint8_t buf[256] = {};

    fipr.engine_id = 1;
    EncodeFipr(&fipr, buf);
    fipr.engine_id = 0;
    DecodeFipr(&fipr, buf);
    EXPECT_EQ(fipr.engine_id, 1);

    fipr.engine_id = 2;
    DecodeFipr(&fipr, buf);
    EXPECT_EQ(fipr.engine_id, 1); // FAILED, It's 3

    fipr.engine_id = 8;
    EncodeFipr(&fipr, buf);
    fipr.engine_id = 0;
    DecodeFipr(&fipr, buf);
    EXPECT_EQ(fipr.engine_id, 8); // FAILED, It's 9
}

TEST(BitProto, 1) {
    Flit flit{};
    uint8_t buf[256] = {};

    flit.dw0 = 1;
    EncodeFlit(&flit, buf);
    flit.dw0 = 0;
    DecodeFlit(&flit, buf);
    EXPECT_EQ(flit.dw0, 1);

    flit.dw0 = 2;
    EncodeFlit(&flit, buf);
    flit.dw0 = 0;
    DecodeFlit(&flit, buf);
    EXPECT_EQ(flit.dw0, 2);

    flit.dw0 = 4;
    EncodeFlit(&flit, buf);
    flit.dw0 = 0;
    DecodeFlit(&flit, buf);
    EXPECT_EQ(flit.dw0, 4);
}
```

The implementation of `BpCopyBufferBits` in `lib/c/bitproto.c` make this happen.

What do you think? Is this ambiguity reasonable?

**Comment by hit9** [comment]
Hi, sorry for this late response.

The target struct's memory should be cleared before `DecodeXXX` function is called.

bitproto only touches the target bits, other bits are left unchanged. So, for the not byte-aligned fields, when the target struct is dirty with some pre-filled data there, `DecodeXXX` goses unexpected results.

For an example, here's an `uint8_t` integer in C, `a = 11`, its  binary representation in 8bits width is (lower bits on the right)

```
00001011
```

Say its  integer  type in bitproto definition is `uint3.
So what if we decode a buffer `00000001` onto it?

Only the lowest 3bits are taken care of, **the other bits aren't**, they're left unchanged, the result is:

```
00001001
```

Thus, the result is unexpected if we decode a buffer into a dirty struct.

**Comment by zzz00yx** [comment]
> Hi, sorry for this late response.
> 
> The target struct's memory should be cleared before `DecodeXXX` function is called.
> 
> bitproto only touches the target bits, other bits are left unchanged. So, for the not byte-aligned fields, when the target struct is dirty with some pre-filled data there, `DecodeXXX` goses unexpected results.
> 
> For an example, here's an `uint8_t` integer in C, `a = 11`, its binary representation in 8bits width is (lower bits on the right)
> 
> ```
> 00001011
> ```
> 
> Say its integer type in bitproto definition is `uint3`. So what if we decode a buffer `00000001` onto it?
> 
> Only the lowest 3bits are taken care of, **the other bits aren't**, they're left unchanged, the result is:
> 
> ```
> 00001001
> ```
> 
> Thus, the result is unexpected if we decode a buffer into a dirty struct.

Emmm. If that's what you say, then it's not a problem.
This is me reproducing the case you described. Take a look and see if it conveys the meaning you intended.
```
// bitproto
message A {
    uint3 a = 1
}

// c
void main() {
    struct A a = {};
    a.a = 0b00001011;
    uint8_t s1[1] = {0b00000001};
    DecodeA(&a, s1);
    assert(a.a == 0b00001001); // Failed, a.a is 0b00001011
}
```

**Comment by hit9** [comment]
I have implemented in C for the standard mode in this commit https://github.com/hit9/bitproto/commit/99f18248d63fa6ec38601b68d89c909c0733fe2a

It works well but the benchmark on stm32 shows that the encoding/decoding per call costs about 10us more now.

**Comment by zzz00yx** [comment]
I added a comment to your commit : ) 
https://github.com/hit9/bitproto/commit/99f18248d63fa6ec38601b68d89c909c0733fe2a#r107054190

**Comment by zzz00yx** [comment]
Just out of curiosity. Why don't you generate C strurct with bit fields? Isn't it faster?
