### ISSUE TITLE
Auto-generate rst documentation for serialization structures

### ISSUE THREAD

**Issue by mprudky** [hit9/bitproto#56]
Add a script, which will allow to generate .rst documentation for the given bit proto schema.

Rationale: Schemas often represents messages being exchanged between the devices and messages needs documentation in human readable form. Bitproto already supports generation of the serialization/deserialization source code. Having auto generation of the documentation should add additional great value to the bitproto.

**Comment by hit9** [comment]
Nice idea, but I don't have time to do it.

Pull requests are welcome :)
